set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports {blue_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red_o[0]}]
set_property PACKAGE_PIN F5 [get_ports {red_o[4]}]
set_property PACKAGE_PIN C6 [get_ports {red_o[3]}]
set_property PACKAGE_PIN C5 [get_ports {red_o[2]}]
set_property PACKAGE_PIN B7 [get_ports {red_o[1]}]
set_property PACKAGE_PIN K2 [get_ports {red_o[0]}]
set_property PACKAGE_PIN B6 [get_ports {green_o[5]}]
set_property PACKAGE_PIN A6 [get_ports {green_o[4]}]
set_property PACKAGE_PIN A5 [get_ports {green_o[3]}]
set_property PACKAGE_PIN D8 [get_ports {green_o[2]}]
set_property PACKAGE_PIN J2 [get_ports {green_o[1]}]
set_property PACKAGE_PIN J3 [get_ports {green_o[0]}]
set_property PACKAGE_PIN C7 [get_ports {blue_o[4]}]
set_property PACKAGE_PIN E6 [get_ports {blue_o[3]}]
set_property PACKAGE_PIN E5 [get_ports {blue_o[2]}]
set_property PACKAGE_PIN E7 [get_ports {blue_o[1]}]
set_property PACKAGE_PIN H4 [get_ports {blue_o[0]}]
set_property PACKAGE_PIN D7 [get_ports hsync_out]
set_property PACKAGE_PIN C4 [get_ports vsync_out]
set_property PACKAGE_PIN R11 [get_ports right]
set_property PACKAGE_PIN V1 [get_ports left]
set_property PACKAGE_PIN U4 [get_ports rotateL]
set_property PACKAGE_PIN R17 [get_ports rotateR]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property PACKAGE_PIN R15 [get_ports enter]
set_property IOSTANDARD LVCMOS33 [get_ports enter]
set_property IOSTANDARD LVCMOS33 [get_ports hsync_out]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property IOSTANDARD LVCMOS33 [get_ports rotateL]
set_property IOSTANDARD LVCMOS33 [get_ports rotateR]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports vsync_out]


set_property IOSTANDARD LVCMOS33 [get_ports KB_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports KB_DATA]

set_property PACKAGE_PIN K5 [get_ports KB_CLK]
set_property PACKAGE_PIN L4 [get_ports KB_DATA]

set_property PACKAGE_PIN U4 [get_ports down]
set_property PACKAGE_PIN R17 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports up]
